#!/usr/bin/env bash
# This script reads /etc/passwd line by line and displays user information

while IFS=':' read -r user pass uid gid comment home shell; do
    echo "$user:$uid:$home"
done < /etc/passwd
